// 根目录 build.gradle
buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // 使用与 Gradle 8.x 兼容的 AGP 插件版本
        classpath 'com.android.tools.build:gradle:8.2.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
