plugins {
    id 'com.android.application'
}

android {
    namespace 'com.audiosplitter.status'
    compileSdk 34

    defaultConfig {
        applicationId "com.audiosplitter.status"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
    }

    // 忽略预检报错，防止警告导致编译中断
    lintOptions {
        checkReleaseBuilds false
        abortOnError false
    }

    signingConfigs {
        release {
            storeFile file("${rootDir}/release.keystore")
            storePassword "123456"
            keyAlias "key0"
            keyPassword "123456"
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.11.0'
}
